### ISSUE TITLE
investigate `const generics` for `EventQueue` and `Slab`

### ISSUE THREAD

**Issue by lidatong** [foonetic/agnostic-orderbook#14]
Currently both the event queue and bid/ask critbits hold opaque buffer (`[u8]`) and a lot of manual fudging with bytes. It's difficult to understand and error-prone.

Rust introduced a feature `const generics` which I have not really used, but I _think_ may be able to help us. Briefly:

```rust
struct ArrayPair<T, const N: usize> {
    left: [T; N]
}
```

> We know `N` is bounded, given Solana's limits on BPF memory usage - given `N` we can also express transformations like `N-1`

Specifically if we can work with `[Event; N]` instead of `[u8]` (and have Anchor code-gen the zero-copy serde, types of `next_account_info`, etc.) I think this could greatly help both the understandability and correctness of the API.

**Comment by yuhanfang** [comment]
Huh. I didn't realize that wasn't already a Rust feature.

For the Serum-specific use case, do we even need this to be generic, or can N just be some const? For generalizing beyond this one application it does seem useful to let users specify different N.

**Comment by lidatong** [comment]
oh to clarify it's not brand new -- it was released to stable last year perhaps you remember it

re Serum: yes `N` could be a constant since we know exactly what metadata we'll need
- assuming we make the change to fix the size of the event queue to "3 size fits all" as discussed in #13 (vs. current serum where you specify the event queue's size  in `create_market`)

re "agnostic" / other apps: yeah, it will need to be generic because user can specify arbitrary-length metadata in an `Event` (though we could make that 3-size fits all too)

**Comment by yuhanfang** [comment]
Got it. Sounds useful. Thanks for looking into it.

**Comment by lidatong** [comment]
Closing -- this experiment with `const generics` didn't really work well with Anchor. Details here: https://github.com/foonetic/agnostic-orderbook/pull/13#issuecomment-1046296376
