### ISSUE TITLE
consider refactoring to Anchor

### ISSUE THREAD

**Issue by lidatong** [foonetic/agnostic-orderbook#6]
I'd like to propose we consider refactoring the AOB on-chain program to use Anchor:
- AOB already sort of uses it's own Anchor-esque macro generation (see `bonfida_utils::InstructionAccount`)
  - But it doesn't actually "give you types", as everything is still just an `AccountInfo` and you have to manually `impl` how to parse the `accounts_iter`
- A few benefits of Anchor
  - "Real types" when passing around accounts
  - Declarative specification of PDAs, account initialization, checks, etc. (separate from orderbook processor logic)
  - IDL (makes writing JS clients a lot easier and less boilerplatey)
  - Toolchain (`anchor test` is quite a nice experience, feels just like browser hot-reloading) 
  - Eliminate a lot of boilerplate and reduce size of the codebase

Downside is Anchor will require use to think about the discriminant when writing client code that does not use Anchor's built-in client. And as with any refactor we will have to test to make sure it didn't break anything (but the test coverage and usage is arguably not that great to begin with)

Please comment, especially if you don't think this is a good idea

**Comment by yuhanfang** [comment]
I think this is a fantastic idea. https://github.com/foonetic/anchor-serum
